run:
  timeout: 5m
  skip-files:
    - ".*_test\\.go"

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - typecheck

linters-settings:
  goimports:
    local-prefixes: github.com/SwellNetwork/hyperliquid-go-sdk
  revive:
    confidence: 0.8

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
